plugins/OldDsw/config/routes.php
<?php
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::plugin(
    'OldDsw',
    ['path' => '/old-dsw'],
    function (RouteBuilder $routes) {
        $routes->fallbacks(DashedRoute::class);
    }
);

plugins/OldDsw/src/Model/Table/ZadostiTable.php
<?php

namespace OldDsw\Model\Table;

use Cake\Datasource\EntityInterface;
use Cake\ORM\Association\BelongsTo;
use Cake\ORM\Association\HasMany;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use OldDsw\Model\Entity\Zadost;

/**
 * Zadosti Model
 *
 * @property UctyTable&BelongsTo $Ucets
 * @property PrilohyTable&HasMany $PrilohyZadosti
 * @property OhlasovaciFormularTable&HasMany $OhlasovaciFormular
 *
 * @method Zadost get($primaryKey, $options = [])
 * @method Zadost newEntity($data = null, array $options = [])
 * @method Zadost[] newEntities(array $data, array $options = [])
 * @method Zadost|false save(EntityInterface $entity, $options = [])
 * @method Zadost saveOrFail(EntityInterface $entity, $options = [])
 * @method Zadost patchEntity(EntityInterface $entity, array $data, array $options = [])
 * @method Zadost[] patchEntities($entities, array $data, array $options = [])
 * @method Zadost findOrCreate($search, callable $callback = null, $options = [])
 */
class ZadostiTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('zadosti');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
        $this->setEntityClass('OldDsw.Zadost');

        $this->belongsTo('Ucet', [
            'foreignKey' => 'ucet_id',
            'joinType' => 'INNER',
            'className' => 'OldDsw.Ucty',
        ]);
        $this->belongsTo('Fond', [
            'foreignKey' => 'fond_id',
            'className' => 'OldDsw.Fondy',
        ]);
        $this->belongsTo('Program', [
            'foreignKey' => 'program_id',
            'className' => 'OldDsw.Programy',
        ]);
        $this->belongsTo('Ucel', [
            'foreignKey' => 'ucel_id',
            'className' => 'OldDsw.Ucely',
        ]);
        $this->hasOne('DefiniceProjektu', [
            'foreignKey' => 'zadost_id',
            'className' => 'OldDsw.DefiniceProjektu',
        ]);
        $this->hasOne('RozpoctyProjektu', [
            'foreignKey' => 'zadost_id',
            'className' => 'OldDsw.RozpoctyProjektu',
        ]);
        $this->hasMany('OhlasovaciFormular', [
            'foreignKey' => 'zadost_id',
            'className' => 'OldDsw.OhlasovaciFormular',
        ]);
        $this->hasMany('PrilohyZadosti', [
            'foreignKey' => 'request_id',
            'className' => 'OldDsw.Prilohy',
        ]);
        $this->hasOne('PrilohyFormulareProhlaseniOVerejnePodpore', [
            'foreignKey' => 'zadost_id',
            'className' => 'OldDsw.PrilohyFormulareProhlaseniOVerejnePodpore',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param Validator $validator Validator instance.
     * @return Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->nonNegativeInteger('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('nazev')
            ->maxLength('nazev', 255)
            ->notEmptyString('nazev');

        $validator
            ->numeric('pozadovana_castka')
            ->notEmptyString('pozadovana_castka');

        $validator
            ->numeric('navrhovana_castka')
            ->notEmptyString('navrhovana_castka');

        $validator
            ->numeric('konecna_castka')
            ->notEmptyString('konecna_castka');

        $validator
            ->scalar('status')
            ->maxLength('status', 45)
            ->notEmptyString('status');

        $validator
            ->scalar('verejny_status')
            ->maxLength('verejny_status', 45)
            ->notEmptyString('verejny_status');

        $validator
            ->nonNegativeInteger('pocet_bodu')
            ->notEmptyString('pocet_bodu');

        $validator
            ->dateTime('pridano')
            ->notEmptyDateTime('pridano');

        $validator
            ->nonNegativeInteger('pridano_kym')
            ->notEmptyString('pridano_kym');

        $validator
            ->dateTime('posledni_uprava_kdy')
            ->allowEmptyDateTime('posledni_uprava_kdy');

        $validator
            ->nonNegativeInteger('posledni_uprava_kym')
            ->allowEmptyString('posledni_uprava_kym');

        $validator
            ->boolean('uzamceno')
            ->notEmptyString('uzamceno');

        $validator
            ->dateTime('uzamknout_kdy')
            ->allowEmptyDateTime('uzamknout_kdy');

        $validator
            ->scalar('poznamka_spravy')
            ->requirePresence('poznamka_spravy', 'create')
            ->notEmptyString('poznamka_spravy');

        $validator
            ->scalar('cislo_jednaci')
            ->maxLength('cislo_jednaci', 45)
            ->allowEmptyString('cislo_jednaci');

        $validator
            ->date('datum_podani')
            ->allowEmptyDate('datum_podani');

        $validator
            ->nonNegativeInteger('dotacni_obdobi')
            ->notEmptyString('dotacni_obdobi');

        $validator
            ->boolean('smazano')
            ->notEmptyString('smazano');

        $validator
            ->dateTime('smazano_kdy')
            ->allowEmptyDateTime('smazano_kdy');

        $validator
            ->integer('smazano_kym')
            ->allowEmptyString('smazano_kym');

        $validator
            ->boolean('odeslano')
            ->notEmptyString('odeslano');

        $validator
            ->dateTime('odeslano_kdy')
            ->allowEmptyDateTime('odeslano_kdy');

        $validator
            ->integer('odeslano_kym')
            ->allowEmptyString('odeslano_kym');

        $validator
            ->scalar('cislo_uctu')
            ->maxLength('cislo_uctu', 30)
            ->allowEmptyString('cislo_uctu');

        $validator
            ->scalar('ratingMessage')
            ->maxLength('ratingMessage', 300)
            ->allowEmptyString('ratingMessage');

        $validator
            ->scalar('short_purpouse')
            ->maxLength('short_purpouse', 300)
            ->allowEmptyString('short_purpouse');

        $validator
            ->scalar('econom_status')
            ->maxLength('econom_status', 300)
            ->allowEmptyString('econom_status');

        $validator
            ->scalar('final_report')
            ->maxLength('final_report', 300)
            ->allowEmptyString('final_report');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param RulesChecker $rules The rules object to be modified.
     * @return RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['ucet_id'], 'Ucet'));
        $rules->add($rules->existsIn(['fond_id'], 'Fond'));
        $rules->add($rules->existsIn(['program_id'], 'Program'));
        $rules->add($rules->existsIn(['ucel_id'], 'Ucel'));

        return $rules;
    }

    /**
     * Returns the database connection name to use by default.
     *
     * @return string
     */
    public static function defaultConnectionName()
    {
        return 'dsw';
    }
}

plugins/OldDsw/src/Template/Element/ohlaseni.ctp
<?php
/**
 * @var $this AppView
 * @var $ohlaseni OhlasovaciFormular
 */

use App\View\AppView;
use Cake\I18n\Number;
use OldDsw\Model\Entity\OhlasovaciFormular;

$typy_ohlaseni = [
    0 => 'akce',
    1 => 'dílo',
    2 => 'celoroční činnost'
];
$card = (isset($card) && is_bool($card)) ? $card : false;

?>

<?php if ($card): ?>
    <div class="card">
    <div class="card-header">
<?php endif; ?>
    <strong>Ohlášení (odesláno <?= $ohlaseni->added_when ? $ohlaseni->added_when->nice() : '' ?>)</strong>
<?php if ($card): ?>
    </div>
    <div class="card-body">
    <table class="table">
        <tr>
            <td><strong>Zahájení</strong></td>
            <td><?= $ohlaseni->datum_zahajeni ? $ohlaseni->datum_zahajeni->nice() : '' ?></td>
        </tr>
        <tr>
            <td><strong>Ukončení</strong></td>
            <td><?= $ohlaseni->datum_ukonceni ? $ohlaseni->datum_ukonceni->nice() : '' ?></td>
        </tr>
        <tr>
            <td><strong>Typ ohlášení</strong></td>
            <td><?= $typy_ohlaseni[$ohlaseni->typ] ?></td>
        </tr>
        <tr>
            <td><strong>Místo konání</strong></td>
            <td><?= $ohlaseni->misto_konani ?></td>
        </tr>
        <tr>
            <td><strong>Garant</strong></td>
            <td><?= sprintf("%s (%s %s)", $ohlaseni->garant, $ohlaseni->garant_telefon, $ohlaseni->garant_email) ?></td>
        </tr>
        <tr>
            <td><strong>Poznámka</strong></td>
            <td><?= $ohlaseni->poznamka ?></td>
        </tr>
        <tr>
            <td><strong>Předpokládaný počet účastníků</strong></td>
            <td><?= $ohlaseni->pocet_ucastniku ?></td>
        </tr>
        <tr>
            <td><strong>Čerpaná částka</strong></td>
            <td><?= Number::currency($ohlaseni->cerpana_castka, 'CZK') ?></td>
        </tr>
        <tr>
            <td><strong>Příloha</strong></td>
            <td><?= empty($ohlaseni->prilohy) ? 'Bez přílohy' : $ohlaseni->prilohy->orig_filename ?></td>
        </tr>
    </table>
<?php endif; ?>
<?php if ($card): ?>
    </div>
    </div>
<?php endif; ?>

plugins/OldDsw/src/Template/Element/ucet.ctp
<?php
/**
 * @var $this AppView
 * @var $ucet Ucet
 */

if (!isset($ucet) || empty($ucet)) {
    return;
}

use App\View\AppView;
use OldDsw\Model\Entity\Ucet;

?>
<div class="row">
    <div class="col-md-6">
        <table class="table">
            <tr>
                <td>
                    <?= __d('olddsw', 'Název') ?>
                </td>
                <td>
                    <?= $ucet->nazev ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?= __d('olddsw', 'Právní Forma') ?>
                </td>
                <td>
                    <?= $ucet->pravni_forma ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?= __d('olddsw', 'Adresa') ?>
                </td>
                <td>
                    <?= $ucet->formatAddress() ?>
                </td>
            </tr>
            <?php if (!$ucet->isPO()): ?>
                <tr>
                    <td>
                        <?= __d('olddsw', 'Adresa doručovací') ?>
                    </td>
                    <td>
                        <?= $ucet->formatDorucovaciAddress() ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= __d('olddsw', 'Datum Narození') ?>
                    </td>
                    <td>
                        <?= empty($ucet->fyzicke_osoby) ? '' : $ucet->fyzicke_osoby[0]->datum_narozeni ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= __d('olddsw', 'Číslo OP') ?>
                    </td>
                    <td>
                        <?= empty($ucet->fyzicke_osoby) ? '' : $ucet->fyzicke_osoby[0]->cislo_OP ?>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <td>
                    <?= __d('olddsw', 'Telefon') ?>
                </td>
                <td>
                    <?= $ucet->telefon ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?= __d('olddsw', 'Email') ?>
                </td>
                <td>
                    <?= $ucet->email ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?= __d('olddsw', 'IČO') ?>
                </td>
                <td>
                    <?= $ucet->dic ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?= __d('olddsw', 'DIČ') ?>
                </td>
                <td>
                    <?= $ucet->ico ?>
                </td>
            </tr>
        </table>
        <?php if ($ucet->isPO() && !empty($ucet->statutarni_organ)): ?>
            <strong>Statutární orgán, osoby zastupující právnickou osobu</strong>
            <table class="table">
                <tr>
                    <td>Jméno a Příjmení</td>
                    <td><?= $ucet->statutarni_organ[0]->formatFullName() ?></td>
                </tr>
                <tr>
                    <td>Právní důvod zastoupení</td>
                    <td><?= $ucet->statutarni_organ[0]->funkce ?></td>
                </tr>
                <tr>
                    <td>Telefon</td>
                    <td><?= $ucet->statutarni_organ[0]->telefon ?></td>
                </tr>
                <tr>
                    <td>E-mail</td>
                    <td><?= $ucet->statutarni_organ[0]->email ?></td>
                </tr>
            </table>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <table class="table">
            <tr>
                <td>
                    <?= __d('olddsw', 'Bankovní spojení') ?>
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    <?= __d('olddsw', 'Název Banky') ?>
                </td>
                <td>
                    <?= $ucet->nazev_banky ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?= __d('olddsw', 'Číslo účtu / Kód banky') ?>
                </td>
                <td>
                    <?= $ucet->cislo_uctu . '/' . $ucet->kod_banky ?>
                </td>
            </tr>
        </table>
    </div>
</div>

plugins/OldDsw/src/Template/Element/zadost.ctp
<?php
/**
 * @var $this AppView
 * @var $zadost Zadost
 */

if (!isset($zadost) || empty($zadost)) {
    return;
}

use App\View\AppView;
use Cake\I18n\Number;
use Cake\Routing\Router;
use OldDsw\Model\Entity\Zadost;

?>

<div class="card mt-2">
    <h2 class="card-header">Žádost</h2>
    <div class="card-body">
        <table class="table">
            <tr>
                <td><strong>Název projektu</strong></td>
                <td><?= $zadost->nazev ?></td>
                <td><strong>Identifikační číslo žádosti</strong></td>
                <td><?= $zadost->id ?></td>
            </tr>
        </table>
    </div>
</div>
<div class="card mt-2">
    <h2 class="card-header">Žadatel</h2>
    <div class="card-body">
        <?= $this->element('OldDsw.ucet', ['ucet' => $zadost->ucet]) ?>
    </div>
</div>
<div class="card mt-2">
    <h2 class="card-header">Základní informace</h2>
    <div class="card-body">
        <div class="row">
            <div class="col-md">
                <table class="table">
                    <tr>
                        <td><strong>Název dotačního programu</strong></td>
                        <td><?= $zadost->fond ? $zadost->fond->name : __('N/A') ?></td>
                    </tr>
                    <tr>
                        <td><strong>Oblast dotačního programu</strong></td>
                        <td><?= $zadost->program ? $zadost->program->name : __('N/A') ?></td>
                    </tr>
                    <tr>
                        <td><strong>Účel</strong></td>
                        <td><?= $zadost->ucel ? $zadost->ucel->name : __('N/A') ?></td>
                    </tr>
                    <tr>
                        <td><strong>Prohlášení o veřejné podpoře</strong></td>
                        <td><?= $zadost->prilohy_formulare_prohlaseni_o_verejne_podpore ? $zadost->prilohy_formulare_prohlaseni_o_verejne_podpore->summary() : '' ?></td>
                    </tr>
                    <tr>
                        <td colspan="2"><strong>Účel, oblast a cíl projektu, zdůvodnění a předpokládaný
                                přínos</strong></td>
                    </tr>
                    <?php if ($zadost->definice_projektu): ?>
                        <tr>
                            <td colspan="2">
                                <?= $zadost->definice_projektu->ucel ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                </table>
            </div>
            <?php if ($zadost->definice_projektu): ?>
                <div class="col-md">
                    <table class="table">
                        <tr>
                            <td colspan="2"><strong>Vztah projektu k MČ Praha 3</strong></td>
                        </tr>
                        <tr>
                            <td colspan="2"><?= $zadost->definice_projektu->vztah_k_Praha_3 ?></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <div class="row">
                                    <div class="col-md"><strong>Předpokládané zahájení</strong></div>
                                    <div class="col-md"><strong>Místo realizace</strong></div>
                                    <div class="col-md"><strong>Předpokládané ukončení</strong></div>
                                </div>
                                <?php if ($zadost->definice_projektu && $zadost->definice_projektu->terminy): ?>
                                    <div class="row">
                                        <div class="col-md"><?= $zadost->definice_projektu->terminy->zahajeni ?></div>
                                        <div class="col-md"><?= $zadost->definice_projektu->terminy->misto_realizace ?></div>
                                        <div class="col-md"><?= $zadost->definice_projektu->terminy->ukonceni ?></div>
                                    </div>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2"><strong>Dosavadní činnost žadatele</strong></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <?= str_replace('\n', '<br/>', $zadost->definice_projektu->dosavadni_cinnost) ?>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2"><strong>Konkrétní účel použití fin. prostředků v souladu s rozpočtem a
                                    zásadami pro příslušný program</strong></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <?= str_replace('\n', '<br/>', $zadost->definice_projektu->pouziti_financi) ?>
                            </td>
                        </tr>
                    </table>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php if ($zadost->rozpocty_projektu): ?>
    <div class="card mt-2">
        <h2 class="card-header">Rozpočet projektu</h2>
        <div class="card-body">
            <table class="table">
                <tr>
                    <td><strong>Celkové náklady projektu</strong></td>
                    <td><?= Number::currency($zadost->rozpocty_projektu->celkove_naklady, 'CZK') ?></td>
                </tr>
                <tr>
                    <td><strong>Celkové výnosy projektu</strong></td>
                    <td><?= Number::currency($zadost->rozpocty_projektu->celkove_vynosy, 'CZK') ?></td>
                </tr>
                <tr>
                    <td><strong>Požadovaná výše dotace</strong></td>
                    <td><?= Number::currency($zadost->pozadovana_castka, 'CZK') ?></td>
                </tr>
            </table>
            <strong>Vlastní Zdroje</strong>
            <table class="table">
                <?php $vlastni_zdroje_celkem = 0;
                foreach ($zadost->rozpocty_projektu->rozpocty_projektu_vlastni_zdroje as $vlastni_zdroj):
                    $vlastni_zdroje_celkem += $vlastni_zdroj->castka; ?>
                    <tr>
                        <td><?= $vlastni_zdroj->nazev ?></td>
                        <td><?= Number::currency($vlastni_zdroj->castka, 'CZK') ?></td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td><strong>Vlastní Zdroje Celkem</strong></td>
                    <td><strong><?= Number::currency($vlastni_zdroje_celkem, 'CZK') ?></strong></td>
                </tr>
            </table>
            <strong>Dotace z jiných zdrojů - včetně podaných žádostí</strong>
            <table class="table">
                <tr>
                    <td><strong>Ministerstva ČR</strong></td>
                    <td><?= Number::currency($zadost->rozpocty_projektu->dotace_z_ministerstva_cr, 'CZK') ?></td>
                </tr>
                <tr>
                    <td><strong>EU</strong></td>
                    <td><?= Number::currency($zadost->rozpocty_projektu->dotace_z_eu, 'CZK') ?></td>
                </tr>
                <tr>
                    <td><strong>MHMP</strong></td>
                    <td><?= Number::currency($zadost->rozpocty_projektu->dotace_z_mhmp, 'CZK') ?></td>
                </tr>
                <?php foreach ($zadost->rozpocty_projektu->rozpocty_projektu_jine_zdroje as $jiny_zdroj): ?>
                    <tr>
                        <td><strong><?= $jiny_zdroj->nazev ?></strong></td>
                        <td><?= Number::currency($jiny_zdroj->castka, 'CZK') ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>

    <div class="card mt-2">
        <h2 class="card-header">Ekonomická rozvaha</h2>
        <div class="card-body">
            <div class="row">
                <div class="col-md">
                    <strong>Položkový rozpis výnosů</strong>
                    <table class="table">
                        <?php foreach ($zadost->rozpocty_projektu->rozpocty_projektu_vynosy as $vynos): ?>
                            <tr>
                                <td><?= $vynos->nazev ?></td>
                                <td><?= Number::currency($vynos->castka, 'CZK') ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
                <div class="col-md">
                    <strong>Položkový rozpis nákladů</strong>
                    <table class="table">
                        <?php foreach ($zadost->rozpocty_projektu->rozpocty_projektu_naklady as $naklad): ?>
                            <tr>
                                <td><?= $naklad->nazev ?></td>
                                <td><?= Number::currency($naklad->castka, 'CZK') ?></td>
                            </tr>
                        <?php endforeach; ?>
                        <?php foreach ($zadost->rozpocty_projektu->rozpocty_projektu_naklady_investicni as $naklad): ?>
                            <tr>
                                <td><?= $naklad->nazev ?></td>
                                <td><?= Number::currency($naklad->castka, 'CZK') ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-md">
                    <strong>Bilance (výnosy minus náklady)</strong>
                </div>
                <div class="col-md text-right font-weight-bold">
                    <?= Number::currency($zadost->rozpocty_projektu->celkove_vynosy - $zadost->rozpocty_projektu->celkove_naklady, 'CZK') ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if (false): ?>
    <div class="card mt-2">
        <h4 class="card-header">Přehled obdržených finančních prostředků z rozpočtu MČ Praha 3, MHMP nebo státního
            rozpočtu v posledních dvou letech.</h4>
        <div class="card-body">

        </div>
    </div>
<?php endif; ?>

<div class="card mt-2">
    <h2 class="card-header">Hodnocení</h2>
    <div class="card-body">
        <table class="table">
            <tr>
                <td><strong>Slovní komentář</strong></td>
                <td><strong>Výsledné hodnocení</strong></td>
            </tr>
            <tr>
                <td>
                    <?= $zadost->ratingMessage ?>
                </td>
                <td>
                    <?= $zadost->pocet_bodu ?>
                </td>
            </tr>
        </table>
    </div>
</div>

<?php if (!empty($zadost->ohlasovaci_formular)): ?>
    <div class="card mt-2">
        <h2 class="card-header">Ohlášení akce/činnosti</h2>
        <div class="card-body">
            <?php foreach ($zadost->ohlasovaci_formular as $ohlaseni): ?>
                <?= $this->element('OldDsw.ohlaseni', compact('ohlaseni')) ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<div class="card mt-2">
    <h2 class="card-header">Přílohy žádosti</h2>
    <div class="card-body">
        <table class="table">
            <thead>
            <tr>
                <th>Typ Přílohy</th>
                <th>Soubor</th>
                <th>Velikost</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($zadost->prilohy_zadosti as $priloha): ?>
                <tr>
                    <td><?= $priloha->identifier ?></td>
                    <td><?= Router::routeExists(['action' => 'dswDownload', $priloha->id]) ? $this->Html->link($priloha->orig_filename, ['action' => 'dswDownload', $priloha->id], ['target' => '_blank']) : h($priloha->orig_filename) ?></td>
                    <td><?= round($priloha->filesize / 1024 / 1024, 2) ?> MB</td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

plugins/OldDsw/src/Template/Element/zadosti.ctp
<?php
/**
 * @var $this AppView
 * @var $zadosti Zadost[]
 */

if (!isset($zadosti) || empty($zadosti)) {
    return;
}

use App\View\AppView;
use Cake\I18n\Number;
use Cake\Routing\Router;
use OldDsw\Model\Entity\Zadost;

?>
<table class="table" id="dtable">
    <thead>
    <tr>
        <th><?= __d('olddsw', 'Název') ?></th>
        <th><?= __d('olddsw', 'Program') ?></th>
        <th><?= __d('olddsw', 'Účel') ?></th>
        <th><?= __d('olddsw', 'Dotační Období') ?></th>
        <th><?= __d('olddsw', 'Požadovaná výše dotace') ?></th>
        <th><?= __d('olddsw', 'Navrhovaná výše dotace') ?></th>
        <th><?= __d('olddsw', 'Konečná výše dotace') ?></th>
        <th><?= __d('olddsw', 'Ohlášeno') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($zadosti as $zadost): ?>
        <?php if (empty($zadost) || !isset($zadost->nazev) || empty($zadost->nazev)) {
            continue;
        } ?>
        <tr>
            <td><?= $this->Html->link($zadost->nazev, ['action' => 'dswZadost', $zadost->id]) ?></td>
            <td><?= $zadost->program ? $zadost->program->name : __('N/A') ?></td>
            <td><?= $zadost->ucel ? $zadost->ucel->name : __('N/A') ?></td>
            <td><?= $zadost->dotacni_obdobi ?></td>
            <td><?= Number::currency($zadost->pozadovana_castka, 'CZK') ?></td>
            <td><?= Number::currency($zadost->navrhovana_castka, 'CZK') ?></td>
            <td><?= Number::currency($zadost->konecna_castka, 'CZK') ?></td>
            <td class="text-center">
                <span class="d-none"><?= empty($zadost->ohlasovaci_formular) ? '1' : '0' ?></span>
                <?php if (empty($zadost->ohlasovaci_formular) && Router::routeExists(['action' => 'dswOhlasit', $zadost->id])): ?>
                    <?= $this->Html->link(__('Ohlásit akci/činnost'), ['action' => 'dswOhlasit', $zadost->id], ['class' => 'text-success']) ?>
                <?php else: ?>
                    <button type="button" data-toggle="modal" data-target="#modal-<?= $zadost->id ?>"
                            class="btn pr-2 <?= empty($zadost->ohlasovaci_formular) ? 'btn-danger' : 'btn-success' ?>">
                        &nbsp;
                    </button>
                    <?php if (!empty($zadost->ohlasovaci_formular)): ?>
                        <div class="modal fade" id="modal-<?= $zadost->id ?>" tabindex="-1" role="dialog"
                             aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <?php if (Router::routeExists(['action' => 'dswOhlasit', $zadost->id])) {
                                        echo $this->Html->link(__('Ohlásit akci/činnost'), ['action' => 'dswOhlasit', $zadost->id], ['class' => 'btn btn-success']);
                                        echo '<hr/>';
                                    }
                                    ?>
                                    <?php foreach ($zadost->ohlasovaci_formular as $ohlaseni) {
                                        echo $this->element('OldDsw.ohlaseni', ['ohlaseni' => $ohlaseni, 'card' => true]);
                                    } ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>